### ISSUE TITLE
xss case

### ISSUE THREAD

**Issue by moreJs** [cujanovic/Markdown-XSS-Payloads#1]
[a](j    a   v   a   s   c   r   i   p   t:prompt(document.cookie)) 
how to reappear this xss case?
thanks a lot.

**Comment by cujanovic** [comment]
https://archive.fo/czTWm

**Comment by moreJs** [comment]
@cujanovic  i just confused about [a](j a v a s c r i p t:prompt(document.cookie)), does this is xss case?

**Comment by cujanovic** [comment]
from the blogpost:
"The above vectors target edge cases and a majority of Markdown libraries."
Now I don't understand your question here.
Clearly some Markdown lib was/is vulnerable to this payload.
My guess is that the string "    " bypasses the filter that is probably doing some regex or matching for javascript string.
